### PR TITLE
ref: upgrade isort to work around poetry breakage 

### PR DESCRIPTION
**Pull request by asottile-sentry**
https://github.com/python-poetry/poetry-core/pull/542

Committed via https://github.com/asottile/all-repos

### CODE REVIEW

**Review by evanh — APPROVED** [review]

**Comment by asottile-sentry** [comment]
@evanh I can't seem to merge here -- is the repo set to require up-to-date branches?

**Comment by evanh** [comment]
Yes it does. Should we remove that?

**Comment by asottile-sentry** [comment]
that's what I'd recommend heh -- you can check the box that *allows* that dropdown to be there, but I find requiring it is a really bad experience (I shouldn't have to rebase every open PR because someone fixed a typo for example)

**Comment by evanh** [comment]
OK well @lynnagara is the owner of this repo. I'll let her make the call.

**Comment by lynnagara** [comment]
Disabled the rule, it's mergeable without updating now.

**Pull request merged**
