### PR TITLE
fix(docs) Fix makefile

### PR DESCRIPTION
**Pull request by fpacifici**
We cannot call the Makefile target for docs `docs` as there is a directory named `docs`

### CODE REVIEW

**Review by volokluev — APPROVED** [review]

**Review by lynnagara — CHANGES_REQUESTED** [review]
Can we add docs to PHONY target instead?

**Comment by fpacifici** [comment]
That may work, let me see

**Comment by fpacifici** [comment]
yeah, it works

**Review by lynnagara — APPROVED** [review]
Thanks

**Pull request merged**
